### ISSUE TITLE
solarflow-bt-manager when do I need it?

### ISSUE THREAD

**Issue by joe63** [reinhard-brandstaedter/solarflow-bt-manager#16]
Hallo,
Do I need the solarflow-bt-manager only to disconnect(or connect) your SF Hub from(to) the cloud or even to receive the mqtt-messages to my iobrocker?

Or is the communication between HUB2000 and my iobrocker via WiFi
On my q920 (where docker runs) there is no capable  Bluetooth LE device (at this time).
So I would run the solarflow-bt-manager  on a second computer only when I want to disconnect or connect the SF HUB fron/to cloud.

Thanks

BR J

**Comment by reinhard-brandstaedter** [comment]
Yes as described [here](https://github.com/reinhard-brandstaedter/solarflow-bt-manager?tab=readme-ov-file#offline-mode).
Just disconnect via. BT device (eg. radpi zero) and then only reuse that device for reconnecting.
