### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by picatextra** [reinhard-brandstaedter/solarflow-bt-manager#2]
After i disconnected the Hub , it sent one event to my MQTT broker
<img width="310" alt="image" src="https://github.com/reinhard-brandstaedter/solarflow-bt-manager/assets/4353090/55261427-adb9-417a-b034-7cac81119639">

But when i try to change the output Limit , the property is not affected

**Comment by picatextra** [comment]
It looks like i cant do offline MQTT broker (bluetooth)  and  publish _iot_  (Wifi)  at the same time
<img width="577" alt="image" src="https://github.com/reinhard-brandstaedter/solarflow-bt-manager/assets/4353090/f005d3ef-f4ac-40b8-83fa-7820de2850df">
i succes to change output limit while solarflow-bt-manager is not running

So now my question is how do you run solarflow-control  + solarflow-status + solarflow-bt-manager in offline mode all together :)

**Comment by reinhard-brandstaedter** [comment]
If you use bt-manager in proxy mode it relays commands to the zendure cloud via the status page only.
For permanent control via solarflow-control you should take the hub offline ( no need to keep bt-manager running) and your hub will only be controlled via local mqtt.

FYI: the hub can only be controlled either via BT OR WiFi (not both at the same time). If the hub has a BT client connected it ignores everything in MQTT.
