### ISSUE TITLE
How to use solarflow-bt-manager with multiple SolarFlow Hubs?

### ISSUE THREAD

**Issue by codenyte** [reinhard-brandstaedter/solarflow-bt-manager#29]

**Comment by reinhard-brandstaedter** [comment]
As its main purpose is to disconnect the hub from the cloud, you can do this one by one. Turn off hub1, disconnect it from cloud and then proceed with hub2 while hub1 is off.
It's not intended to run bt-manager in proxy mode 24x7 anyway.

**Comment by reinhard-brandstaedter** [comment]
Correct, once disconnected it will remember those settings.
If you want to do a firmware upgrade I recommend to do this via the Zendure App using the bluetooth connection (BT will still be active while your hub is disconnected from the cloud)
