### ISSUE TITLE
not compatible with latest paho-mqtt 2.0.0

### ISSUE THREAD

**Issue by axelmaurer** [reinhard-brandstaedter/solarflow-bt-manager#4]
Hi,

Thank you for the development! It seems that the current version is not compatible with the latest version of paho-mqtt. In the file requierments.txt I had to replace the line "paho-mqtt" with "paho-mqtt==1.6.1".

**Comment by reinhard-brandstaedter** [comment]
Thanks for bringing this up!

**Comment by busaku** [comment]
I think its fixed :)

**Comment by tuxianerDE** [comment]
@busaku can you please close the issue if it is resolved :)
